In [1]:
from pathlib import Path
import pandas as pd
pd.set_option('max_colwidth', 100)
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm, datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import label_binarize
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import confusion_matrix
import itertools
import scipy.stats as st
import pandas as pd
import numpy as np
from scipy import stats
from sklearn.feature_selection import mutual_info_classif
import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 500)
import rpy2
import pingouin as pg

In [2]:
# ICC - https://www.uvm.edu/~statdhtx/methods8/Supplements/icc/More%20on%20ICCs.pdf
# ICC(2,1) - Each subject is measured by each rater, and raters are considered representative
#            of a larger population of similar raters. 
#            Reliability calculated from a single measurement.

# I found two python implementations:
#     1 - pinguoin 
#     https://pingouin-stats.org/build/html/generated/pingouin.intraclass_corr.html
#     2 - R thorugh rpy2
#     https://www.r-bloggers.com/2021/06/intraclass-correlation-coefficient-in-r-quick-guide/
#     also:
#     https://stackoverflow.com/questions/40965579/intraclass-correlation-in-python-module

# ICC(2,1) for : 
# total score of HITOP
# total score of BAARS
# each subscale of HITOP
# each subscale of BAARS-IV
# GAD-7
# PHQ-8

In [3]:
#path_to_save_logs = 'logs/logs_icc/'
log_dir = Path('./log')
dat_dir = Path('../data/')
val_dir = dat_dir / 'ValSample'
fin_dir = dat_dir / 'finaldata'
cfa_dir = dat_dir / 'cfa'
icc_dir = dat_dir / 'icc'
icc_dir.mkdir(exist_ok=True)
path_to_save_logs = log_dir / 'logs_final/logs_icc/'
path_to_save_logs.mkdir(exist_ok=True, parents=True)

# Load data; very light processing

In [4]:
# path where data are saved
path_save_dat_gp_gridall_full = fin_dir / 'dat_gp_gridall_full.csv'
path_save_dat_en_gridall_full = fin_dir / 'dat_en_gridall_full.csv'

# load from csv
data_gp = pd.read_csv(path_save_dat_gp_gridall_full, index_col=0)
data_en = pd.read_csv(path_save_dat_en_gridall_full, index_col=0)

# create subject id column
data_gp = data_gp.rename(columns={'caseid': 'Subject'})
data_en = data_en.rename(columns={'caseid': 'Subject'})

# combine data
data_combined = pd.concat([data_gp, data_en])

# ---- Invariant cores from the measEq pipeline ----
# final_cores (NB_2_cfa_as_reg's stepwise_scalar.pkl): one row per HiTOP
# scale with core_level ('scalar' = scalar core; 'metric' = metric
# fallback; None = no invariant core found), the core item set, and the
# items removed relative to the original scale.
final_cores = pd.read_pickle(cfa_dir / 'stepwise_scalar.pkl')

# gp_en stepwise cores (NB_2_cfa_as_reg_gp_en): the PREREGISTERED core set
# for the combined-sample ICCs ("invariant core between the general
# population and enriched samples") -- all 14 scales reach scalar level.
gp_en_cores_sw = pd.read_pickle(dat_dir / 'cfa_gp_en' / 'stepwise_scalar.pkl')

# EN-VAL pairwise stepwise cores (NB_2_cfa_as_reg_en_val): exploratory
# third core set for the ICC comparison.
enval_cores_sw = pd.read_pickle(dat_dir / 'cfa_en_val' / 'stepwise_scalar.pkl')

# other scales (PHQ / GAD / BAARS subscales): STEPWISE cores from the
# gp_en-only pipeline (NB_2_cfa_as_reg_other_gp_en). Author decision
# 2026-08: cores are stepwise-only throughout -- the exhaustive alternates
# (exhaustive.pkl / other_scales_exhaustive.pkl) are no longer consumed
# here. PHQ's core is the stepwise METRIC fallback; core_level is carried
# so downstream consumers can apply the scalar-only reporting rule.
other_cores = pd.read_pickle(dat_dir / 'cfa_other_gp_en' / 'stepwise_scalar.pkl')

In [5]:
# ---- Unified core assembly (HiTOP cores and other-scale cores handled
# ---- through the same derivation) ----
# Reporting rule (HANDOFF_measeq_fix.md): ICCs may use metric-fallback
# cores, but clinical-vs-HV latent mean comparisons are reported ONLY for
# scales with core_level == 'scalar'. core_level is carried on every row
# so downstream consumers can apply that rule.
core_cols = ['scale', 'core_level', 'item_nos', 'removed_nos', 'items', 'removed']

# HiTOP cores: the stepwise deliverable per scale (scalar core, or metric
# fallback). Scales with core_level None have no invariant core and are
# excluded here (they only appear as original scales in section 1).
# PRIMARY (preregistered for combined-sample ICC): the gp_en stepwise
# cores. Reduced cores get the downstream naming convention
# 'hitop_{scale}__invcore'; full-scale cores keep the bare scale name
# (their sum scores already exist as the hitop_{scale} columns used in
# section 1).
hitop_cores = gp_en_cores_sw.loc[
    gp_en_cores_sw.core_level.notnull(), core_cols].copy()
if 'error' in gp_en_cores_sw.columns:
    hitop_cores['error'] = gp_en_cores_sw.loc[hitop_cores.index, 'error']
hitop_cores['confirmatory'] = True
hitop_cores['core_set'] = 'gp_en'
hitop_cores['inv'] = True
hitop_cores['reduced'] = hitop_cores.removed_nos.map(len) > 0
hitop_cores.loc[hitop_cores.reduced, 'scale'] = (
    'hitop_' + hitop_cores.loc[hitop_cores.reduced, 'scale'] + '__invcore')

# SECONDARY (exploratory for ICC purposes; stricter derivation): the
# triply invariant (validation/GP/EN) stepwise cores. Only reduced rows
# are carried (a bare-name full-scale row would collide with the gp_en
# set); suffix '__3way_invcore' keeps them distinct downstream.
hitop_3way = final_cores.loc[final_cores.core_level.notnull(),
                             core_cols].copy()
if 'error' in final_cores.columns:
    hitop_3way['error'] = final_cores.loc[hitop_3way.index, 'error']
hitop_3way['reduced'] = hitop_3way.removed_nos.map(len) > 0
hitop_3way = hitop_3way.loc[hitop_3way.reduced].copy()
hitop_3way['scale'] = 'hitop_' + hitop_3way['scale'] + '__3way_invcore'
hitop_3way['confirmatory'] = True
hitop_3way['core_set'] = '3way'
hitop_3way['inv'] = True

# TERTIARY (exploratory): the EN-VAL pairwise stepwise cores. Reduced
# rows only, suffix '__enval_invcore'.
hitop_enval = enval_cores_sw.loc[enval_cores_sw.core_level.notnull(),
                                 core_cols].copy()
if 'error' in enval_cores_sw.columns:
    hitop_enval['error'] = enval_cores_sw.loc[hitop_enval.index, 'error']
hitop_enval['reduced'] = hitop_enval.removed_nos.map(len) > 0
hitop_enval = hitop_enval.loc[hitop_enval.reduced].copy()
hitop_enval['scale'] = 'hitop_' + hitop_enval['scale'] + '__enval_invcore'
hitop_enval['confirmatory'] = False
hitop_enval['core_set'] = 'en_val'
hitop_enval['inv'] = True

# Other scales (PHQ / GAD / BAARS): same shape and naming convention as the
# HiTOP cores. These come from the gp_en-only STEPWISE run
# (confirmatory=False; single-pair evidence).
# stepwise picks; reduced rows only (full-scale other scales keep their
# existing sum columns), actual core_level carried (phq_sum is 'metric').
other_to_merge = other_cores.loc[
    other_cores.core_level.notnull()
    & (other_cores.removed_nos.map(len) > 0),
    ['scale', 'core_level', 'item_nos', 'removed_nos', 'items', 'removed']].copy()
other_to_merge['item_nos'] = other_to_merge.item_nos.map(list)
other_to_merge['scale'] = other_to_merge.scale + '__invcore'
other_to_merge['confirmatory'] = False
other_to_merge['core_set'] = 'other_gp_en'
other_to_merge['inv'] = True
other_to_merge['reduced'] = True

cores = pd.concat([hitop_cores, hitop_3way, hitop_enval, other_to_merge],
                  ignore_index=True)
cores.to_pickle(cfa_dir / 'consolidated_cores.pkl')
cores

,scale,core_level,item_nos,removed_nos,items,removed,error,confirmatory,core_set,inv,reduced
0,hitop_anhedonic_depression__invcore,scalar,"[hitop39, hitop123, hitop182, hitop230, hitop246]","[hitop77, hitop84, hitop92, hitop93, hitop157]","[It felt like there wasn’t anything interesting or fun to do., Nothing made me laugh., I was una...","[I didn’t look forward to seeing friends or family., I felt depressed., It took a lot of effort ...",None,True,gp_en,True,True
1,hitop_anxious_worry__invcore,scalar,"[hitop34, hitop89, hitop240, hitop248, hitop265]","[hitop20, hitop203]","[Thoughts were racing through my head., I had a lot of nervous energy., I felt nervous and ""on e...","[I felt tense., I felt very stressed.]",None,True,gp_en,True,True
2,hitop_appetite_gain__invcore,scalar,"[hitop120, hitop243, hitop275]",[hitop141],"[I could not keep myself from eating., I stuffed myself with food., I ate even when I was not re...",[I thought a lot about food.],None,True,gp_en,True,True
3,appetite_loss,scalar,"[hitop280, hitop283, hitop109]",[],"[My appetite was poor., I lost a significant amount of weight without even trying., I did not fe...",[],None,True,gp_en,True,False
4,cognitive_problems,scalar,"[hitop67, hitop159, hitop189, hitop142]",[],"[I could not stay focused on what I was doing., I was unable to keep my mind on what I was doing...",[],None,True,gp_en,True,False
5,hitop_hyposomnia__invcore,scalar,"[hitop99, hitop5, hitop66]","[hitop181, hitop231]","[I needed much less sleep than usual., I had days when I never got tired., I did not feel tired,...","[I felt like I could keep going and going without ever getting tired., I felt like I could go fo...",None,True,gp_en,True,True
6,indecisiveness,scalar,"[hitop21, hitop90, hitop95]",[],"[I was indecisive., It was difficult for me to make decisions., I had trouble making up my mind.]",[],None,True,gp_en,True,False
7,hitop_insomnia__invcore,scalar,"[hitop160, hitop254, hitop268]",[hitop261],"[I had trouble staying asleep., I slept very poorly., I lay awake for a long time before falling...",[I woke up early and could not get back to sleep.],None,True,gp_en,True,True
8,panic,scalar,"[hitop15, hitop104, hitop126, hitop211, hitop215, hitop257]",[],"[I was short of breath., I felt nauseated., My heart was racing or pounding., I was trembling or...",[],None,True,gp_en,True,False
9,separation_insecurity,scalar,"[hitop40, hitop50, hitop69, hitop81, hitop113, hitop136, hitop151, hitop197]",[],"[I felt insecure about important relationships in my life., I wanted someone else to make decisi...",[],None,True,gp_en,True,False
10,hitop_shame_guilt__invcore,scalar,"[hitop72, hitop140, hitop143]",[hitop220],"[I was disgusted with myself., I blamed myself for things., I felt guilty.]",[I felt ashamed of things I had done.],None,True,gp_en,True,True
11,hitop_situational_phobia__invcore,scalar,"[hitop16, hitop165, hitop247]","[hitop225, hitop278]","[I avoided riding in elevators., I was afraid of flying., I was afraid of heights.]","[I was afraid of the dark., I became very anxious during a storm.]",None,True,gp_en,True,True
12,hitop_social_anxiety__invcore,scalar,"[hitop17, hitop114, hitop124, hitop236, hitop258]","[hitop1, hitop117, hitop129, hitop204, hitop222]","[I was uncomfortable meeting new people., I had difficulty making eye contact with others., I av...","[I felt shy around other people., I felt socially awkward., I avoided performing or giving a tal...",None,True,gp_en,True,True
13,hitop_well_being__invcore,scalar,"[hitop9, hitop23, hitop54, hitop244, hitop281]","[hitop106, hitop149, hitop200, hitop245, hitop250]","[I felt like I was having a lot of fun., I felt cheerful., It was easy for me to laugh., I felt ...","[I was proud of myself., I felt good about myself., I found compliments very encouraging., I loo...",None,True,gp_en,True,True
14,hitop_anhedonic_depression__3way_invcore,metric,"[hitop77, hitop84, hitop92, hitop123, hitop182, hitop230]","[hitop39, hitop93, hitop157, hitop246]","[I didn’t look forward to seeing friends or family., I felt depressed., It took a lot of effort ...","[It felt like there wasn’t anything interesting or fun to do., Nothing seemed interesting to me....",NaN,True,3way,True,True
15,hitop_anxious_worry__3way_invcore,metric,"[hitop240, hitop248, hitop265]","[hitop20, hitop34, hitop89, hitop203]","[I felt nervous and ""on edge""., I worried about almost everything., I was overwhelmed by anxiety.]","[I felt tense., Thoughts were racing through my head., I had a lot of nervous energy., I felt ve...",NaN,True,3way,True,True
16,hitop_appetite_gain__3way_invcore,metric,"[hitop141, hitop243, hitop275]",[hitop120],"[I thought a lot about food., I stuffed myself with food., I ate even when I was not really hung...",[I could not keep myself from eating.],NaN,True,3way,True,True
17,hitop_hyposomnia__3way_invcore,metric,"[hitop99, hitop5, hitop66, hitop231]",[hitop181],"[I needed much less sleep than usual., I had days when I never got tired., I did not feel tired,...",[I felt like I could keep going and going without ever getting tired.],NaN,True,3way,True,True
18,hitop_insomnia__3way_invcore,scalar,"[hitop160, hitop254, hitop268]",[hitop261],"[I had trouble staying asleep., I slept very poorly., I lay awake for a long time before falling...",[I woke up early and could not get back to sleep.],NaN,True,3way,True,True
19,hitop_panic__3way_invcore,scalar,"[hitop104, hitop126, hitop215]","[hitop15, hitop211, hitop257]","[I felt nauseated., My heart was racing or pounding., My hands were cold or sweaty.]","[I was short of breath., I was trembling or shaking., I felt dizzy or lightheaded.]",NaN,True,3way,True,True
20,hitop_separation_insecurity__3way_invcore,scalar,"[hitop40, hitop69, hitop81, hitop136, hitop151, hitop197]","[hitop50, hitop113]","[I felt insecure about important relationships in my life., I wanted other people to take care o...","[I wanted someone else to make decisions for me., I could not handle rejection.]",NaN,True,3way,True,True
21,hitop_social_anxiety__3way_invcore,metric,"[hitop114, hitop124, hitop129, hitop204, hitop222, hitop236]","[hitop1, hitop17, hitop117, hitop258]","[I had difficulty making eye contact with others., I avoided situations in which others were lik...","[I felt shy around other people., I was uncomfortable meeting new people., I felt socially awkwa...",NaN,True,3way,True,True
22,hitop_well_being__3way_invcore,metric,"[hitop23, hitop149, hitop250]","[hitop9, hitop54, hitop106, hitop200, hitop244, hitop245, hitop281]","[I felt cheerful., I felt good about myself., I felt like I had a lot of interesting things to do.]","[I felt like I was having a lot of fun., It was easy for me to laugh., I was proud of myself., I...",NaN,True,3way,True,True
23,hitop_anhedonic_depression__enval_invcore,scalar,"[hitop77, hitop123, hitop230]","[hitop39, hitop84, hitop92, hitop93, hitop157, hitop182, hitop246]","[I didn’t look forward to seeing friends or family., Nothing made me laugh., I felt emotionally ...","[It felt like there wasn’t anything interesting or fun to do., I felt depressed., It took a lot ...",NaN,False,en_val,True,True
24,hitop_anxious_worry__enval_invcore,scalar,"[hitop20, hitop203, hitop265]","[hitop34, hitop89, hitop240, hitop248]","[I felt tense., I felt very stressed., I was overwhelmed by anxiety.]","[Thoughts were racing through my head., I had a lot of nervous energy., I felt nervous and ""on e...",NaN,False,en_val,True,True
25,hitop_hyposomnia__enval_invcore,scalar,"[hitop99, hitop181, hitop66]","[hitop5, hitop231]","[I needed much less sleep than usual., I felt like I could keep going and going without ever get...","[I had days when I never got tired., I felt like I could go for days without sleeping.]",NaN,False,en_val,True,True
26,hitop_insomnia__enval_invcore,scalar,"[hitop160, hitop254, hitop268]",[hitop261],"[I had trouble staying asleep., I slept very poorly., I lay awake for a long time before falling...",[I woke up early and could not get back to sleep.],NaN,False,en_val,True,True
27,hitop_panic__enval_invcore,scalar,"[hitop15, hitop104, hitop126, hitop211, hitop215]",[hitop257],"[I was short of breath., I felt nauseated., My heart was racing or pounding., I was trembling or...",[I felt dizzy or lightheaded.],NaN,False,en_val,True,True
28,hitop_separation_insecurity__enval_invcore,scalar,"[hitop40, hitop50, hitop69, hitop81, hitop136, hitop151, hitop197]",[hitop113],"[I felt insecure about important relationships in my life., I wanted someone else to make decisi...",[I could not handle rejection.],NaN,False,en_val,True,True
29,hitop_situational_phobia__enval_invcore,scalar,"[hitop16, hitop165, hitop225, hitop247]",[hitop278],"[I avoided riding in elevators., I was afraid of flying., I was afraid of the dark., I was afrai...",[I became very anxious during a storm.],NaN,False,en_val,True,True
30,hitop_social_anxiety__enval_invcore,scalar,"[hitop114, hitop129, hitop204, hitop222, hitop258]","[hitop1, hitop17, hitop117, hitop124, hitop236]","[I had difficulty making eye contact with others., I avoided performing or giving a talk in fron...","[I felt shy around other people., I was uncomfortable meeting new people., I felt socially awkwa...",NaN,False,en_val,True,True
31,hitop_well_being__enval_invcore,scalar,"[hitop106, hitop149, hitop200, hitop250]","[hitop9, hitop23, hitop54, hitop244, hitop245, hitop281]","[I was proud of myself., I felt good about myself., I found compliments very encouraging., I fel...","[I felt like I was having a lot of fun., I felt cheerful., It was easy for me to laugh., I felt ...",NaN,False,en_val,True,True
32,phq_sum__invcore,metric,"[phq_1, phq_3, phq_4, phq_6, phq_7]","[phq_2, phq_5, phq_8]","[Little interest or pleasure in doing things, Trouble falling or staying asleep, or sleeping too...","[Feeling down, depressed, irritable or hopeless, Poor appetite or overeating, Moving or speaking...",NaN,False,other_gp_en,True,True
33,baars_inattention_sum__invcore,scalar,"[inattention_3, inattention_4, inattention_5, inattention_6, inattention_7, inattention_8]","[inattention_1, inattention_2, inattention_9]","[Don't listen when spoken to directly, Don't follow through on instructions and fail to finish w...",[Fail to give close attention to details or make careless mistakes in my work or other activitie...,NaN,False,other_gp_en,True,True
34,baars_sct_sum__invcore,scalar,"[sct_1, sct_3, sct_4, sct_5, sct_6, sct_8]","[sct_2, sct_7, sct_9]","[Prone to daydreaming when I should be concentrating on something or working, Easily confused, E...","[Have trouble staying alert or awake in boring situations, Underactive or have less energy than ...",NaN,False,other_gp_en,True,True

In [6]:
#cores = pd.read_pickle(cfa_dir / 'consolidated_cores.pkl')

In [7]:
path_to_cogmood_questions = dat_dir / 'cogmood_questions.csv'
path_to_item_lookup = val_dir / 'Internalizing-Somatoform Items_DW.xlsx'

In [8]:
cores_long = []
for row in cores.itertuples():
    for item_no, item in zip(row.item_nos, row.items):
        clrow = dict(
            scale=row.scale,
            item_no=item_no,
            item=item
        )
        cores_long.append(clrow)
cores_long = pd.DataFrame(cores_long)
cores_long.to_csv(cfa_dir / 'consolidated_cores_long.tsv', sep='\t', index=None)

In [9]:
cores.loc[cores.scale.str.startswith('hitop_separation'), :]

,scale,core_level,item_nos,removed_nos,items,removed,error,confirmatory,core_set,inv,reduced
20,hitop_separation_insecurity__3way_invcore,scalar,"[hitop40, hitop69, hitop81, hitop136, hitop151, hitop197]","[hitop50, hitop113]","[I felt insecure about important relationships in my life., I wanted other people to take care o...","[I wanted someone else to make decisions for me., I could not handle rejection.]",NaN,True,3way,True,True
28,hitop_separation_insecurity__enval_invcore,scalar,"[hitop40, hitop50, hitop69, hitop81, hitop136, hitop151, hitop197]",[hitop113],"[I felt insecure about important relationships in my life., I wanted someone else to make decisi...",[I could not handle rejection.],NaN,False,en_val,True,True

In [10]:
 cores.loc[cores.scale.str.startswith('hitop_well')]

,scale,core_level,item_nos,removed_nos,items,removed,error,confirmatory,core_set,inv,reduced
13,hitop_well_being__invcore,scalar,"[hitop9, hitop23, hitop54, hitop244, hitop281]","[hitop106, hitop149, hitop200, hitop245, hitop250]","[I felt like I was having a lot of fun., I felt cheerful., It was easy for me to laugh., I felt ...","[I was proud of myself., I felt good about myself., I found compliments very encouraging., I loo...",None,True,gp_en,True,True
22,hitop_well_being__3way_invcore,metric,"[hitop23, hitop149, hitop250]","[hitop9, hitop54, hitop106, hitop200, hitop244, hitop245, hitop281]","[I felt cheerful., I felt good about myself., I felt like I had a lot of interesting things to do.]","[I felt like I was having a lot of fun., It was easy for me to laugh., I was proud of myself., I...",NaN,True,3way,True,True
31,hitop_well_being__enval_invcore,scalar,"[hitop106, hitop149, hitop200, hitop250]","[hitop9, hitop23, hitop54, hitop244, hitop245, hitop281]","[I was proud of myself., I felt good about myself., I found compliments very encouraging., I fel...","[I felt like I was having a lot of fun., I felt cheerful., It was easy for me to laugh., I felt ...",NaN,False,en_val,True,True

In [11]:
cores.to_pickle(icc_dir / 'cores.pkl')

# Functions

In [12]:
path_to_cogmood_questions = dat_dir / 'cogmood_questions.csv'
path_to_item_lookup = val_dir / 'Internalizing-Somatoform Items_DW.xlsx'
def load_item_lookup():
    # this is a table that aligns scale items with their corresponding questions
    htqs = pd.read_excel(path_to_item_lookup, skiprows=2,
                                names=['id', 'scale', 'item', '_0', '_1', '_2', '_3']).drop(['_0', '_1', '_2', '_3'], axis=1)
    # cmqs is a dataframe with items and responses
    # htcm is the same dataframe, but only displaying HiTOP items
    cmqs = pd.read_csv(path_to_cogmood_questions)
    cmqs = cmqs.rename({'Unnamed: 0': 'id'}, axis=1)
    htcm = cmqs.query("measure == 'HiTOP'")
    # this is a lookup table for subscales, items (sentence questions), and hitop ids
    item_lookup = htcm.loc[:, ['id','subscale', 'item']].merge(htqs.loc[:, ['id','item']], how='inner', on='item', suffixes=['_cm', '_ht'])
    item_lookup['htid'] = 'hitop'+ item_lookup.id_ht.astype(str)
    return(item_lookup)
item_lookup = load_item_lookup()
item_lut = {row.htid: row.item for row in item_lookup.loc[:, ['item', 'htid']].itertuples()}

def do_icc(data, measure, show = True):
    # just the measure of interest
    data_measure = data[['Subject', measure, measure+'_recontact']]
    data_measure = data_measure.rename(columns={measure: "Original", measure+'_recontact': "Recontact"})
    data_measure_melted = pd.melt(data_measure, id_vars='Subject', value_vars=['Original','Recontact'], value_name='Score')
    data_measure_melted = data_measure_melted.rename(columns={"variable": "Session"})
    # adding Measure - don't really need to do it but eh
    shape = data_measure_melted.shape
    data_measure_melted['Measure'] = [measure] * shape[0]
    #print(measure)
    icc = pg.intraclass_corr(data=data_measure_melted, targets='Subject', raters='Session', ratings='Score').round(4)
    icc.set_index("Type")
    #print(icc)
    if show:
        plt = sns.jointplot(data=data_measure, x='Original', y='Recontact')
        plt.fig.suptitle(measure)
        #plt = plt.set(title=measure)
        #plt.subtitle(measure)
        #plt.show()
        #print(icc)
    return (icc)

def create_table (data, measures):
    df_init = pd.DataFrame()
    for measure in measures:
        if 'bothered' not in measure:
            # print(measure)
            new_icc = do_icc(data, measure, show=False)
            new_icc_row = new_icc.iloc[[1]].copy()
            new_icc_row['Measure'] = measure
            #print(new_icc_row)
            # split CI95 into two cols
            new_icc_row["lci"] = new_icc_row["CI95"].str[0]
            new_icc_row["uci"] = new_icc_row["CI95"].str[1]
            df_init = pd.concat([df_init, new_icc_row], axis = 0)
    df_result = df_init
    return (df_result)

def run_icc_analysis(data, measures):
    for measure in measures:
        if 'bothered' not in measure:
            do_icc(data, measure, show = False) # set show = "True" (default setting) if want to see the individual plots\   
    # organize results neatly
    results_table = create_table(data, measures)
    # put measure first; shift column 'Name' to first position 
    first_column = results_table.pop('Measure') 
    # insert column using insert(position,column_name,first_column) function 
    results_table.insert(0, 'Measure', first_column)
    return (results_table)

/Users/nielsond/code/hitop_val/scalar/.pixi/envs/default/lib/python3.11/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

# Analysis ICC

In [13]:
for ii in item_lookup.query('subscale == "well-being"').sort_values(['subscale', 'id_ht']).item.values:
    print(ii.strip('.'))

I felt like I was having a lot of fun
I felt cheerful
It was easy for me to laugh
I was proud of myself
I felt good about myself
I found compliments very encouraging
I felt optimistic
I looked forward to things with enjoyment
I felt like I had a lot of interesting things to do
I felt that I had a lot to look forward to

In [14]:
# this will be the same for any data (genpop/enriched/combined), so we can go ahead and run it
# instrument-level totals (fixed measures, not subscale outcomes)
measures_for_icc = ['hitop_sum', 'baars_sum', 'phq_sum', 'gad_sum',
                    'baars_inattention_sum', 'baars_hyperactivity_sum',
                    'baars_impulsivity_sum', 'baars_sct_sum']
# per-subscale original-scale sums, generated from the final-cores table
# (one row per HiTOP scale; previously a hardcoded list)
measures_for_icc += [f'hitop_{s}' for s in final_cores.scale]
measures_for_icc

['hitop_sum',
 'baars_sum',
 'phq_sum',
 'gad_sum',
 'baars_inattention_sum',
 'baars_hyperactivity_sum',
 'baars_impulsivity_sum',
 'baars_sct_sum',
 'hitop_anhedonic_depression',
 'hitop_anxious_worry',
 'hitop_appetite_gain',
 'hitop_appetite_loss',
 'hitop_cognitive_problems',
 'hitop_hyposomnia',
 'hitop_indecisiveness',
 'hitop_insomnia',
 'hitop_panic',
 'hitop_separation_insecurity',
 'hitop_shame_guilt',
 'hitop_situational_phobia',
 'hitop_social_anxiety',
 'hitop_well_being']

## 1 - Original scales (not invariant cores)

In [15]:
# -- Orig scales - genpop ---
og_icc_results_gp = run_icc_analysis(data_gp, measures_for_icc)
og_icc_results_gp.to_csv(icc_dir / 'result_ICC_origscales_gp.csv', index=False)

# -- Orig scales - enriched ---
og_icc_results_en = run_icc_analysis(data_en, measures_for_icc)
og_icc_results_en.to_csv(icc_dir / 'result_ICC_origscales_en.csv', index=False)

# -- Orig scales - combined ---
og_icc_results_comb = run_icc_analysis(data_combined, measures_for_icc)
og_icc_results_comb.to_csv(icc_dir / 'result_ICC_origscales_combined.csv', index=False)

# --  Orig scales - combined with enriched for indecisiveness --
og_icc_results_comb.loc[og_icc_results_comb.Measure == 'hitop_indecisiveness', :] = og_icc_results_en.loc[og_icc_results_en.Measure == 'hitop_indecisiveness', :]

og_icc_results_comb.to_csv(icc_dir / 'result_ICC_origscales_forplot_mostcombined_indecivinessenriched.csv', index=False)

In [16]:
og_icc_results_gp

,Measure,Type,ICC,F,df1,df2,pval,CI95,lci,uci
1,hitop_sum,"ICC(A,1)",0.9262,26.1207,397,397,0.0,"[0.91, 0.94]",0.91,0.94
1,baars_sum,"ICC(A,1)",0.8917,17.5091,397,397,0.0,"[0.87, 0.91]",0.87,0.91
1,phq_sum,"ICC(A,1)",0.8850,16.3611,397,397,0.0,"[0.86, 0.9]",0.86,0.90
1,gad_sum,"ICC(A,1)",0.8602,13.2715,397,397,0.0,"[0.83, 0.88]",0.83,0.88
1,baars_inattention_sum,"ICC(A,1)",0.8569,12.9549,397,397,0.0,"[0.83, 0.88]",0.83,0.88
1,baars_hyperactivity_sum,"ICC(A,1)",0.7961,8.8812,397,397,0.0,"[0.76, 0.83]",0.76,0.83
1,baars_impulsivity_sum,"ICC(A,1)",0.7896,8.4910,397,397,0.0,"[0.75, 0.82]",0.75,0.82
1,baars_sct_sum,"ICC(A,1)",0.8681,14.1589,397,397,0.0,"[0.84, 0.89]",0.84,0.89
1,hitop_anhedonic_depression,"ICC(A,1)",0.8893,17.1601,397,397,0.0,"[0.87, 0.91]",0.87,0.91
1,hitop_anxious_worry,"ICC(A,1)",0.8841,16.2318,397,397,0.0,"[0.86, 0.9]",0.86,0.90
1,hitop_appetite_gain,"ICC(A,1)",0.7786,8.0484,397,397,0.0,"[0.74, 0.81]",0.74,0.81
1,hitop_appetite_loss,"ICC(A,1)",0.7689,7.6393,397,397,0.0,"[0.73, 0.81]",0.73,0.81
1,hitop_cognitive_problems,"ICC(A,1)",0.8801,15.6916,397,397,0.0,"[0.86, 0.9]",0.86,0.90
1,hitop_hyposomnia,"ICC(A,1)",0.8073,9.3593,397,397,0.0,"[0.77, 0.84]",0.77,0.84
1,hitop_indecisiveness,"ICC(A,1)",0.8088,9.4572,397,397,0.0,"[0.77, 0.84]",0.77,0.84
1,hitop_insomnia,"ICC(A,1)",0.8050,9.2358,397,397,0.0,"[0.77, 0.84]",0.77,0.84
1,hitop_panic,"ICC(A,1)",0.8366,11.2136,397,397,0.0,"[0.8, 0.86]",0.80,0.86
1,hitop_separation_insecurity,"ICC(A,1)",0.8592,13.1720,397,397,0.0,"[0.83, 0.88]",0.83,0.88
1,hitop_shame_guilt,"ICC(A,1)",0.8487,12.1988,397,397,0.0,"[0.82, 0.87]",0.82,0.87
1,hitop_situational_phobia,"ICC(A,1)",0.7835,8.2284,397,397,0.0,"[0.74, 0.82]",0.74,0.82
1,hitop_social_anxiety,"ICC(A,1)",0.8977,18.5323,397,397,0.0,"[0.88, 0.92]",0.88,0.92
1,hitop_well_being,"ICC(A,1)",0.8737,14.8150,397,397,0.0,"[0.85, 0.9]",0.85,0.90

In [17]:
og_icc_results_en

,Measure,Type,ICC,F,df1,df2,pval,CI95,lci,uci
1,hitop_sum,"ICC(A,1)",0.8369,11.2427,254,254,0.0,"[0.8, 0.87]",0.80,0.87
1,baars_sum,"ICC(A,1)",0.8251,10.3969,254,254,0.0,"[0.78, 0.86]",0.78,0.86
1,phq_sum,"ICC(A,1)",0.8281,10.6985,254,254,0.0,"[0.79, 0.86]",0.79,0.86
1,gad_sum,"ICC(A,1)",0.7563,7.1841,254,254,0.0,"[0.7, 0.8]",0.70,0.80
1,baars_inattention_sum,"ICC(A,1)",0.8219,10.1980,254,254,0.0,"[0.78, 0.86]",0.78,0.86
1,baars_hyperactivity_sum,"ICC(A,1)",0.7229,6.2199,254,254,0.0,"[0.66, 0.78]",0.66,0.78
1,baars_impulsivity_sum,"ICC(A,1)",0.8197,10.0702,254,254,0.0,"[0.77, 0.86]",0.77,0.86
1,baars_sct_sum,"ICC(A,1)",0.7917,8.5851,254,254,0.0,"[0.74, 0.83]",0.74,0.83
1,hitop_anhedonic_depression,"ICC(A,1)",0.8187,10.0051,254,254,0.0,"[0.77, 0.86]",0.77,0.86
1,hitop_anxious_worry,"ICC(A,1)",0.7798,8.0741,254,254,0.0,"[0.73, 0.82]",0.73,0.82
1,hitop_appetite_gain,"ICC(A,1)",0.8456,11.9127,254,254,0.0,"[0.81, 0.88]",0.81,0.88
1,hitop_appetite_loss,"ICC(A,1)",0.7680,7.7261,254,254,0.0,"[0.71, 0.81]",0.71,0.81
1,hitop_cognitive_problems,"ICC(A,1)",0.8071,9.3368,254,254,0.0,"[0.76, 0.85]",0.76,0.85
1,hitop_hyposomnia,"ICC(A,1)",0.7153,6.1178,254,254,0.0,"[0.65, 0.77]",0.65,0.77
1,hitop_indecisiveness,"ICC(A,1)",0.7231,6.2069,254,254,0.0,"[0.66, 0.78]",0.66,0.78
1,hitop_insomnia,"ICC(A,1)",0.7769,7.9461,254,254,0.0,"[0.72, 0.82]",0.72,0.82
1,hitop_panic,"ICC(A,1)",0.8031,9.2581,254,254,0.0,"[0.75, 0.84]",0.75,0.84
1,hitop_separation_insecurity,"ICC(A,1)",0.7996,9.0971,254,254,0.0,"[0.75, 0.84]",0.75,0.84
1,hitop_shame_guilt,"ICC(A,1)",0.7945,8.7423,254,254,0.0,"[0.74, 0.84]",0.74,0.84
1,hitop_situational_phobia,"ICC(A,1)",0.7964,8.8072,254,254,0.0,"[0.75, 0.84]",0.75,0.84
1,hitop_social_anxiety,"ICC(A,1)",0.8248,10.3893,254,254,0.0,"[0.78, 0.86]",0.78,0.86
1,hitop_well_being,"ICC(A,1)",0.7896,8.4786,254,254,0.0,"[0.74, 0.83]",0.74,0.83

In [18]:
og_icc_results_comb

,Measure,Type,ICC,F,df1,df2,pval,CI95,lci,uci
1,hitop_sum,"ICC(A,1)",0.9310,28.0037,652,652,0.0,"[0.92, 0.94]",0.92,0.94
1,baars_sum,"ICC(A,1)",0.9002,19.0484,652,652,0.0,"[0.88, 0.91]",0.88,0.91
1,phq_sum,"ICC(A,1)",0.9068,20.4662,652,652,0.0,"[0.89, 0.92]",0.89,0.92
1,gad_sum,"ICC(A,1)",0.8733,14.7622,652,652,0.0,"[0.85, 0.89]",0.85,0.89
1,baars_inattention_sum,"ICC(A,1)",0.8836,16.1565,652,652,0.0,"[0.87, 0.9]",0.87,0.90
1,baars_hyperactivity_sum,"ICC(A,1)",0.8043,9.2722,652,652,0.0,"[0.78, 0.83]",0.78,0.83
1,baars_impulsivity_sum,"ICC(A,1)",0.8285,10.6452,652,652,0.0,"[0.8, 0.85]",0.80,0.85
1,baars_sct_sum,"ICC(A,1)",0.8799,15.6284,652,652,0.0,"[0.86, 0.9]",0.86,0.90
1,hitop_anhedonic_depression,"ICC(A,1)",0.9041,19.9053,652,652,0.0,"[0.89, 0.92]",0.89,0.92
1,hitop_anxious_worry,"ICC(A,1)",0.8981,18.6324,652,652,0.0,"[0.88, 0.91]",0.88,0.91
1,hitop_appetite_gain,"ICC(A,1)",0.8270,10.5641,652,652,0.0,"[0.8, 0.85]",0.80,0.85
1,hitop_appetite_loss,"ICC(A,1)",0.7849,8.3065,652,652,0.0,"[0.75, 0.81]",0.75,0.81
1,hitop_cognitive_problems,"ICC(A,1)",0.8904,17.2486,652,652,0.0,"[0.87, 0.91]",0.87,0.91
1,hitop_hyposomnia,"ICC(A,1)",0.7655,7.5454,652,652,0.0,"[0.73, 0.8]",0.73,0.80
1,hitop_indecisiveness,"ICC(A,1)",0.7231,6.2069,254,254,0.0,"[0.66, 0.78]",0.66,0.78
1,hitop_insomnia,"ICC(A,1)",0.8194,10.0595,652,652,0.0,"[0.79, 0.84]",0.79,0.84
1,hitop_panic,"ICC(A,1)",0.8560,12.9162,652,652,0.0,"[0.83, 0.88]",0.83,0.88
1,hitop_separation_insecurity,"ICC(A,1)",0.8767,15.2734,652,652,0.0,"[0.86, 0.89]",0.86,0.89
1,hitop_shame_guilt,"ICC(A,1)",0.8658,13.8838,652,652,0.0,"[0.85, 0.88]",0.85,0.88
1,hitop_situational_phobia,"ICC(A,1)",0.8020,9.0898,652,652,0.0,"[0.77, 0.83]",0.77,0.83
1,hitop_social_anxiety,"ICC(A,1)",0.8983,18.6732,652,652,0.0,"[0.88, 0.91]",0.88,0.91
1,hitop_well_being,"ICC(A,1)",0.8654,13.8359,652,652,0.0,"[0.84, 0.88]",0.84,0.88

## 2 - Inv cores

In [19]:
#defrag datasets
data_gp = data_gp.copy()
data_en = data_en.copy()
data_combined = data_combined.copy()
# Sum scores are computed only for REDUCED cores; full-scale cores keep the
# bare scale name and their ICCs come from section 1's precomputed
# hitop_{scale} / *_sum columns. This covers HiTOP and PHQ/GAD/BAARS cores
# through the same code path.
measures_for_icc_invcores = list(cores.loc[cores.reduced, 'scale'])
for data in data_gp, data_en, data_combined:
    for row in cores.loc[cores.reduced, :].itertuples():
        tmp_items = list(row.item_nos)
        tmp_items_recontact = [ti + '_recontact' for ti in tmp_items]
        data[row.scale] = data.loc[:, tmp_items].sum(axis=1)
        data[f'{row.scale}_recontact'] = data.loc[:, tmp_items_recontact].sum(axis=1)

In [20]:
# -- Inv scales - genpop ---
inv_core_icc_results_gp = run_icc_analysis(data_gp, measures_for_icc_invcores)
inv_core_icc_results_gp.to_csv(icc_dir / 'result_ICC_invariantonly_gp.csv', index=False)

# -- Inv scales - enriched ---
inv_core_icc_results_en = run_icc_analysis(data_en, measures_for_icc_invcores)
inv_core_icc_results_en.to_csv(icc_dir / 'result_ICC_invariantonly_en.csv', index=False)

# -- Inv scales - combined ---
inv_core_icc_results_comb = run_icc_analysis(data_combined, measures_for_icc_invcores)
inv_core_icc_results_comb.to_csv(icc_dir / 'result_ICC_invariantonly_combined.csv', index=False)

In [21]:
inv_core_icc_results_comb.sort_values('Measure')

,Measure,Type,ICC,F,df1,df2,pval,CI95,lci,uci
1,baars_inattention_sum__invcore,"ICC(A,1)",0.8628,13.5587,652,652,0.0,"[0.84, 0.88]",0.84,0.88
1,baars_sct_sum__invcore,"ICC(A,1)",0.8635,13.6303,652,652,0.0,"[0.84, 0.88]",0.84,0.88
1,hitop_anhedonic_depression__3way_invcore,"ICC(A,1)",0.8798,15.6232,652,652,0.0,"[0.86, 0.9]",0.86,0.90
1,hitop_anhedonic_depression__enval_invcore,"ICC(A,1)",0.8128,9.6715,652,652,0.0,"[0.79, 0.84]",0.79,0.84
1,hitop_anhedonic_depression__invcore,"ICC(A,1)",0.8534,12.6473,652,652,0.0,"[0.83, 0.87]",0.83,0.87
1,hitop_anxious_worry__3way_invcore,"ICC(A,1)",0.8736,14.8050,652,652,0.0,"[0.85, 0.89]",0.85,0.89
1,hitop_anxious_worry__enval_invcore,"ICC(A,1)",0.8678,14.1383,652,652,0.0,"[0.85, 0.89]",0.85,0.89
1,hitop_anxious_worry__invcore,"ICC(A,1)",0.8847,16.3211,652,652,0.0,"[0.87, 0.9]",0.87,0.90
1,hitop_appetite_gain__3way_invcore,"ICC(A,1)",0.8126,9.6771,652,652,0.0,"[0.78, 0.84]",0.78,0.84
1,hitop_appetite_gain__invcore,"ICC(A,1)",0.8217,10.2220,652,652,0.0,"[0.8, 0.85]",0.80,0.85
1,hitop_hyposomnia__3way_invcore,"ICC(A,1)",0.7466,6.8909,652,652,0.0,"[0.71, 0.78]",0.71,0.78
1,hitop_hyposomnia__enval_invcore,"ICC(A,1)",0.6846,5.3738,652,652,0.0,"[0.64, 0.72]",0.64,0.72
1,hitop_hyposomnia__invcore,"ICC(A,1)",0.6972,5.6025,652,652,0.0,"[0.66, 0.73]",0.66,0.73
1,hitop_insomnia__3way_invcore,"ICC(A,1)",0.8170,9.9176,652,652,0.0,"[0.79, 0.84]",0.79,0.84
1,hitop_insomnia__enval_invcore,"ICC(A,1)",0.8170,9.9176,652,652,0.0,"[0.79, 0.84]",0.79,0.84
1,hitop_insomnia__invcore,"ICC(A,1)",0.8170,9.9176,652,652,0.0,"[0.79, 0.84]",0.79,0.84
1,hitop_panic__3way_invcore,"ICC(A,1)",0.8037,9.1809,652,652,0.0,"[0.77, 0.83]",0.77,0.83
1,hitop_panic__enval_invcore,"ICC(A,1)",0.8413,11.6382,652,652,0.0,"[0.82, 0.86]",0.82,0.86
1,hitop_separation_insecurity__3way_invcore,"ICC(A,1)",0.8550,12.8267,652,652,0.0,"[0.83, 0.87]",0.83,0.87
1,hitop_separation_insecurity__enval_invcore,"ICC(A,1)",0.8730,14.8130,652,652,0.0,"[0.85, 0.89]",0.85,0.89
1,hitop_shame_guilt__invcore,"ICC(A,1)",0.8576,13.0302,652,652,0.0,"[0.84, 0.88]",0.84,0.88
1,hitop_situational_phobia__enval_invcore,"ICC(A,1)",0.7835,8.2269,652,652,0.0,"[0.75, 0.81]",0.75,0.81
1,hitop_situational_phobia__invcore,"ICC(A,1)",0.7365,6.5821,652,652,0.0,"[0.7, 0.77]",0.70,0.77
1,hitop_social_anxiety__3way_invcore,"ICC(A,1)",0.8819,15.9156,652,652,0.0,"[0.86, 0.9]",0.86,0.90
1,hitop_social_anxiety__enval_invcore,"ICC(A,1)",0.8623,13.5063,652,652,0.0,"[0.84, 0.88]",0.84,0.88
1,hitop_social_anxiety__invcore,"ICC(A,1)",0.8794,15.5667,652,652,0.0,"[0.86, 0.9]",0.86,0.90
1,hitop_well_being__3way_invcore,"ICC(A,1)",0.7974,8.8579,652,652,0.0,"[0.77, 0.82]",0.77,0.82
1,hitop_well_being__enval_invcore,"ICC(A,1)",0.8095,9.4859,652,652,0.0,"[0.78, 0.83]",0.78,0.83
1,hitop_well_being__invcore,"ICC(A,1)",0.8369,11.2500,652,652,0.0,"[0.81, 0.86]",0.81,0.86
1,phq_sum__invcore,"ICC(A,1)",0.8976,18.5252,652,652,0.0,"[0.88, 0.91]",0.88,0.91